name: Build & Push Frontend Docker Image

on:
  [push]
    #branches:
     # - main


jobs:
    build-and-push-frontend:
      name: push frontend image to docker hub
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME_ASMA}}
            token: ${{secrets.DOCKERHUB_TOKEN_ASMA}}
          run: |
            docker login -u $username -p $token 
        
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build frontend -f frontend/Dockerfile -t asmabouzidi/frontend-image-test:latest
        
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/frontend-image-test:latest