name: Build & Push Frontend Docker Image

on:
  push:
    branches:
      - feat/GEE-2-build-push-the-docker-image-to-docker-hub-using-github-actions

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME_ASMA }} \
                       -p ${{ secrets.DOCKERHUB_TOKEN_ASMA }}

      - name: Build Docker image
        run: |
          docker build \
            -t asmabouzidi/frontend-image-test:latest \
            -f frontend/Dockerfile \
            frontend

      - name: Push Docker image
        run: |
          docker push asmabouzidi/frontend-image-test:latest
