name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build-frontend:
      name: push frontend docker image to docker hub
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME_ISRA}}
            password: ${{secrets.DOCKERHUB_TOKEN_ISRA}}
          run: |
            docker login -u $username -p $password 
        
        - name: build the frontend docker image
          id: build-frontend-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t israbouzidy/project-frontend:latest
       
        - name: push the docker image
          id: push-frontend-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME_ISRA}}/project-frontend:latest